import Head from 'next/head'
import Footer from '../components/Footer'
import Navbar from '../components/Navbar'


export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <Navbar />
      <main >
      <h1>This is where the content goes</h1>
      </main>
      <Footer />
    </div>
  )
}
