import { google } from 'googleapis';
import Head from 'next/head';
import Image from 'next/image';

export async function getServerSideProps({ query }) {
  const auth = await google.auth.getClient({ scopes: ['https://www.googleapis.com/auth/spreadsheets.readonly'] });

  const sheets = google.sheets({ version: 'v4', auth });

  const response = await sheets.spreadsheets.values.get({
    spreadsheetId: process.env.SHEET_ID,
    range: 'Programs!A:A',
  });

  const posts = response.data.values.flat();
  const att = posts[0];
  const programs = [];
  for(let i = 1; i < posts.length; i++) {
    let temp = {[att]: posts[i]};
    programs.push(temp);
  }
  
  
  return {
    props: {
      programs
    },
  };
}

export default function Home({ programs }) {
  return (
    <div className="container">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="main">
        
      </main>

      <footer className="footer">
This would be the footer
      </footer>
    </div>
  )
}
